config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "current_weather#index", as: :current_weather
  get "forecast", to: "forecast#index", as: :forecast
end

app/models/Address.rb
class Address
  include ActiveModel::Model
  attr_reader :zip
  validates :zip, presence: true, format: { with: /\A\d{5}\z/ }

  def zip=(value)
    @zip = value.to_s[0, 5]
  end
end

app/models/Forecast.rb
class Forecast
  attr_accessor :weather_data, :location, :from_cache
end

app/models/Location.rb
class Location
  attr_accessor :zip, :name, :lat, :lon, :country
  attr_accessor :from_cache
end

app/models/WeatherData.rb
class WeatherData
  attr_accessor :temp, :feels_like, :temp_min, :temp_max, :pressure, :humidity, :wind_speed, :summary, :description
  attr_accessor :is_daytime, :name, :start_time, :end_time, :wind_direction
  attr_accessor :location, :from_cache
end

app/models/WeatherDetail.rb
class WeatherDetail
  attr_accessor :temp, :feels_like, :temp_min, :temp_max, :pressure, :humidity, :wind_speed, :summary, :description
  attr_accessor :is_daytime, :name, :start_time, :end_time, :wind_direction
  attr_accessor :location, :from_cache
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/current_weather_controller.rb
class CurrentWeatherController < ApplicationController
  rescue_from Services::ApiError, with: :api_error
  def index
    @address = Address.new(zip: params[:zip])
    render if params[:zip].nil?
    if @address.valid?
      @current_weather = Services::Hub.new.get_current_weather_for_zip(@address.zip)
    end
  end

  private
  def api_error
    @address.errors.add(:zip, "could not be found, or the OpenWeather API is down.")
    render :index
  end
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
  rescue_from Services::ApiError, with: :api_error

  def index
    @address = Address.new(zip: params[:zip])
    render if params[:zip].nil?
    if @address.valid?
      @forecast = Services::Hub.new.get_forecast_for_zip(@address.zip)
    end
  end

  def api_error
    @address.errors.add(:zip, "could not be found, or a required service is currently down.")
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_temperature(temp)
    "#{temp.to_f.round}° F"
  end
end

app/views/application/_address_form.html.erb
<% if @address.errors.any? %>
  <div>
    <h2><%= pluralize(@address.errors.count, "error") %> prevented the retrieval of weather data.</h2>
    <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with method: :get do |form| %>
  <div>
    <%= form.label :zip, "Zip code:" %>
    <%= form.text_field :zip, value: @address.zip %>
    <%= form.submit "Get Weather", name: nil, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/current_weather/index.html.erb
<h1 class="text-2xl font-semibold leading-6 text-gray-900">Current Weather</h1>

<%= render "application/address_form" %>

<% if @current_weather %>
  <h2>Current weather for: <%= @current_weather.location.name %></h2>
  <p>Summary: <%= @current_weather.summary %></p>
  <p>Description: <%= @current_weather.description %></p>
  <p>From cache: <%= @current_weather.from_cache %></p>
  <ul>
    <li>Temperature: <%= format_temperature(@current_weather.temp) %></li>
    <li>Feels like: <%= format_temperature(@current_weather.feels_like) %></li>
    <li>High: <%= format_temperature(@current_weather.temp_max) %></li>
    <li>Low: <%= format_temperature(@current_weather.temp_min) %></li>
    <li>Pressure: <%= @current_weather.pressure %></li>
    <li>Humidity: <%= @current_weather.humidity %></li>
    <li>Wind speed: <%= @current_weather.wind_speed %></li>
  </ul>
<% end %>

app/views/forecast/index.html.erb
<h1 class="text-2xl font-semibold leading-6 text-gray-900">Forecast</h1>

<%= render "application/address_form" %>

<% if @forecast %>
  <h2>Forecast for: <%= @forecast.location.name %></h2>
  <p>From cache: <%= @forecast.from_cache %></p>
  <% @forecast.weather_data.each do |weather_data| %>
    <div>
      <h3>Weather for: <%= weather_data.name %></h3>
      <p>Summary: <%= weather_data.summary %></p>
      <p>Description: <%= weather_data.description %></p>
      <ul>
        <li>Temperature: <%= format_temperature(weather_data.temp) %></li>
        <li>Wind speed: <%= weather_data.wind_speed %></li>
        <li>Wind direction: <%= weather_data.wind_direction %></li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col space-y-4">
      <div class="flex justify-center space-x-4">
        <%= link_to "Home", current_weather_path, class: "text-blue-500 hover:text-blue-700" %>
        <%= link_to "Current Weather", current_weather_path(request.query_parameters), class: "text-blue-500 hover:text-blue-700" %>
        <%= link_to "Forecast", forecast_path(request.query_parameters), class: "text-blue-500 hover:text-blue-700" %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/weather/index.erb
<h1 class="text-2xl font-semibold leading-6 text-gray-900">Weather</h1>

<% if @location.current_weather %>
  <h2>Current weather for <%= @location.zip %></h2>
  <p>Summary: <%= @location.current_weather.summary %></p>
  <p>Description: <%= @location.current_weather.description %></p>
  <ul>
    <li>Temperature: <%= @location.current_weather.temp %></li>
    <li>Feels like: <%= @location.current_weather.feels_like %></li>
    <li>High: <%= @location.current_weather.temp_max %></li>
    <li>Low: <%= @location.current_weather.temp_min %></li>
    <li>Pressure: <%= @location.current_weather.pressure %></li>
    <li>Humidity: <%= @location.current_weather.humidity %></li>
    <li>Wind speed: <%= @location.current_weather.wind_speed %></li>
    <li>From cache: <%= @location.from_cache %></li>
  </ul>
<% end %>

<% if @location.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@location.errors.count, "error") %> prevented the retrieval of weather data.</h2>
    <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @location, url: weather_path, method: :get, local: true do %>
  <div>
    <%= label_tag :zip, "Zip code:" %>
    <%= text_field_tag :zip, params[:zip] %>
    <%= submit_tag "Get Weather", name: nil, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>